package conversor;

import java.awt.Image;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Moneda extends javax.swing.JPanel {
    String[] paises = {"Seleccione una opción","Dolar", "Euro", "Libra Esterlina", "Yen Japones", "Won sul-coreano"};
    double[] pesoEquivalencia = {0, 0.06, 0.054, 0.046, 8.48, 76.11};
    double[] divisas = {0, 16.71, 18.44, 21.49, 0.117, 0.013};
    private static final String PESO_MEXICANO = "Peso Mexicano";
    
    public Moneda() {
        initComponents();
        comboDivisas();
        
        setImageLabel(divisasImg, "/img/intercambiar.png", 55, 45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textTitulo = new javax.swing.JLabel();
        separador = new javax.swing.JTextField();
        divisasImg = new javax.swing.JLabel();
        labelDe = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        labeImporte = new javax.swing.JLabel();
        fieldImporte = new javax.swing.JTextField();
        labelResultado = new javax.swing.JLabel();
        bttnConvertir = new javax.swing.JButton();
        labelInvertir = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(730, 400));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        textTitulo.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        textTitulo.setForeground(new java.awt.Color(0, 102, 255));
        textTitulo.setText("Conversor de Divisas");

        separador.setEditable(false);
        separador.setBackground(new java.awt.Color(0, 102, 255));
        separador.setBorder(null);
        separador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        divisasImg.setPreferredSize(new java.awt.Dimension(55, 45));

        labelDe.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelDe.setText("De:");

        labelA.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelA.setText("A:");

        combo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        combo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labeImporte.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        labeImporte.setText("Importe:");
        labeImporte.setPreferredSize(new java.awt.Dimension(80, 30));

        fieldImporte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldImporte.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldImporte.setPreferredSize(new java.awt.Dimension(150, 30));

        labelResultado.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(0, 102, 255));
        labelResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelResultado.setPreferredSize(new java.awt.Dimension(80, 30));

        bttnConvertir.setBackground(new java.awt.Color(0, 102, 255));
        bttnConvertir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bttnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        bttnConvertir.setText("Convertir");
        bttnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnConvertirMouseClicked(evt);
            }
        });

        labelInvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flechas.png"))); // NOI18N
        labelInvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelInvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInvertirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(textTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(divisasImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(labelInvertir)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelA, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labeImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bttnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divisasImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDe)
                            .addComponent(labelA))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelInvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bttnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttnConvertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnConvertirMouseClicked
        if ("Peso Mexicano".equals(combo1.getItemAt(0))) {
            conversionMXN(combo2.getSelectedIndex());          
        } else {
            conversionDivisas(combo1.getSelectedIndex());
        }
    }//GEN-LAST:event_bttnConvertirMouseClicked

    private void labelInvertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInvertirMouseClicked
        if ("Peso Mexicano".equals(combo1.getItemAt(0))) {
            invertirDivisas();
            conversionDivisas(combo1.getSelectedIndex());
        } else {
            invertirMexicano();
            conversionMXN(combo2.getSelectedIndex());
        }
    }//GEN-LAST:event_labelInvertirMouseClicked
  
    private void conversionMXN(int op){
        try {
            double importe = Double.parseDouble(fieldImporte.getText());
            double resultado;
            String txtSalida;
            
            switch (op) {
                case 1 -> {
                    resultado = importe * pesoEquivalencia[1];
                    txtSalida = String.format("%.2f Pesos Mexicanos son = %.4f Dolares",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 2 -> {
                    resultado = importe * pesoEquivalencia[2];
                    txtSalida = String.format("%.2f Pesos Mexicanos son = %.4f Euros",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 3 -> {
                    resultado = importe * pesoEquivalencia[3];
                    txtSalida = String.format("%.2f Pesos Mexicanos son = %.4f Libras Esterlinas",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 4 -> {
                    resultado = importe * pesoEquivalencia[4];
                    txtSalida = String.format("%.2f Pesos Mexicanos son = %.4f Yen Japones",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 5 -> {
                    resultado = importe * pesoEquivalencia[5];
                    txtSalida = String.format("%.2f Pesos Mexicanos son = %.4f Won sul-coreano",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                default -> {
                    JOptionPane.showMessageDialog(null, "Seleccione una opción");
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor valido", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            fieldImporte.setText("");
            labelResultado.setText("");
        }
    }
    
    private void conversionDivisas(int op){
        try {
            Double importe = Double.valueOf(fieldImporte.getText());
            double resultado;
            String txtSalida;
            
            switch (op) {
                case 1 -> {
                    resultado = importe * divisas[1];
                    txtSalida = String.format("%.2f Dolares son = %.4f Pesos Mexicanos",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 2 -> {
                    resultado = importe * divisas[2];
                    txtSalida = String.format("%.2f Euros son = %.4f Pesos Mexicanos",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 3 -> {
                    resultado = importe * divisas[3];
                    txtSalida = String.format("%.2f Libras Esterlinas son = %.4f Pesos Mexicanos",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 4 -> {
                    resultado = importe * divisas[4];
                    txtSalida = String.format("%.2f Yen Japones son = %.4f Pesos Mexicanos",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                case 5 -> {
                    resultado = importe * divisas[5];
                    txtSalida = String.format("%.2f Won sul-coreano son = %.4f Pesos Mexicanos",importe, resultado);
                    labelResultado.setText(txtSalida);
                    break;
                }
                default -> {
                    JOptionPane.showMessageDialog(null, "Seleccione una opción");
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor valido", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            labelResultado.setText("");
        }
    }
    
    private void invertirDivisas(){
        int index = combo2.getSelectedIndex();
        combo2.removeAllItems();
        combo2.addItem(PESO_MEXICANO);

        combo1.removeAllItems();
        for (String pais : paises) {
            combo1.addItem(pais);
        }
        combo1.setSelectedIndex(index);
    }
    
    private void invertirMexicano(){
        int index = combo1.getSelectedIndex();
        combo1.removeAllItems();
        combo1.addItem(PESO_MEXICANO);

        combo2.removeAllItems();
        for (String pais : paises) {
            combo2.addItem(pais);
        }
        combo2.setSelectedIndex(index);
    }
    
    private void comboDivisas(){    
        combo1.addItem(PESO_MEXICANO);
        for(String pais: paises){
            combo2.addItem(pais);
        }
    }
    
    private void setImageLabel(JLabel labelName, String root, int width, int height){     
        ImageIcon image = new ImageIcon(Objects.requireNonNull(getClass().getResource(root)));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnConvertir;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JLabel divisasImg;
    private javax.swing.JTextField fieldImporte;
    private javax.swing.JLabel labeImporte;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelDe;
    private javax.swing.JLabel labelInvertir;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField separador;
    private javax.swing.JLabel textTitulo;
    // End of variables declaration//GEN-END:variables


}
