package conversor;

import java.awt.Image;
import java.util.Objects;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Temperatura extends javax.swing.JPanel {
    String[] grados = {"Elija una opción", "Celsius (C)", "Fahrenheit (F)", "Kelvin (K)"};
    
    public Temperatura() {
        initComponents();
        
        setCombos(combo1);
        setCombos(combo2);
        setImageLabel(divisasImg, "/img/termometro.png", 55, 45);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelInvertir = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        combo1 = new javax.swing.JComboBox<>();
        labeImporte = new javax.swing.JLabel();
        fieldImporte = new javax.swing.JTextField();
        labelResultado = new javax.swing.JLabel();
        textTitulo = new javax.swing.JLabel();
        bttnConvertir = new javax.swing.JButton();
        separador = new javax.swing.JTextField();
        divisasImg = new javax.swing.JLabel();
        labelDe = new javax.swing.JLabel();
        labelA = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        labelInvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/flechas.png"))); // NOI18N
        labelInvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelInvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelInvertirMouseClicked(evt);
            }
        });

        combo2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        combo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labeImporte.setFont(new java.awt.Font("Roboto", 0, 22)); // NOI18N
        labeImporte.setText("Importe:");
        labeImporte.setPreferredSize(new java.awt.Dimension(80, 30));

        fieldImporte.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldImporte.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldImporte.setPreferredSize(new java.awt.Dimension(150, 30));

        labelResultado.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelResultado.setForeground(new java.awt.Color(0, 102, 255));
        labelResultado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelResultado.setPreferredSize(new java.awt.Dimension(80, 30));

        textTitulo.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        textTitulo.setForeground(new java.awt.Color(0, 102, 255));
        textTitulo.setText("Conversor de Temperaturas");

        bttnConvertir.setBackground(new java.awt.Color(0, 102, 255));
        bttnConvertir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bttnConvertir.setForeground(new java.awt.Color(255, 255, 255));
        bttnConvertir.setText("Convertir");
        bttnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttnConvertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttnConvertirMouseClicked(evt);
            }
        });

        separador.setEditable(false);
        separador.setBackground(new java.awt.Color(0, 102, 255));
        separador.setBorder(null);
        separador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        divisasImg.setPreferredSize(new java.awt.Dimension(55, 45));

        labelDe.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelDe.setText("De:");

        labelA.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        labelA.setText("A:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(textTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(divisasImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDe, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(labelInvertir)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelA, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labeImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bttnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(divisasImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labeImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDe)
                            .addComponent(labelA))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelInvertir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(bttnConvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void labelInvertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelInvertirMouseClicked
        int indexCombo1 = combo1.getSelectedIndex();
        int indexCombo2 = combo2.getSelectedIndex();
        
        combo1.setSelectedIndex(indexCombo2);
        combo2.setSelectedIndex(indexCombo1);
        
        conversion(combo2.getSelectedIndex());
    }//GEN-LAST:event_labelInvertirMouseClicked

    private void bttnConvertirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttnConvertirMouseClicked
        conversion(combo2.getSelectedIndex());
    }//GEN-LAST:event_bttnConvertirMouseClicked
    
    private void conversion(int op){
        try{
            double grado = Double.parseDouble(fieldImporte.getText());
            String txtSalida;
            
            switch(op){
                case 1 -> {
                    switch (combo1.getSelectedIndex()) {
                        case 1 -> {
                            txtSalida = String.format("%.2f Celsius son = %.2f Celsius",grado, formulasCelsius(grado, 1));
                            labelResultado.setText(txtSalida);
                        }
                        case 2 -> {
                            txtSalida = String.format("%.2f Fahrenheit son = %.2f Celsius",grado, formulasCelsius(grado, 2));
                            labelResultado.setText(txtSalida);
                        }
                        case 3 -> {
                            txtSalida = String.format("%.2f Kelvin son = %.2f Celsius",grado, formulasCelsius(grado, 3));
                            labelResultado.setText(txtSalida);
                        }              
                        default -> {
                            JOptionPane.showMessageDialog(null, "Seleccione una opción");
                        }
                    }
                break;
                }
                
                case 2 -> {
                    switch (combo1.getSelectedIndex()) {
                        case 1 -> {
                            txtSalida = String.format("%.2f Celsius son = %.2f Fahrenheit",grado, formulasFahrenheit(grado, 1));
                            labelResultado.setText(txtSalida);
                        }
                        case 3 -> {
                            txtSalida = String.format("%.2f Kelvin son = %.2f Fahrenheit",grado, formulasFahrenheit(grado, 3));
                            labelResultado.setText(txtSalida);
                        }
                        case 2 -> {
                            txtSalida = String.format("%.2f Fahrenheit son = %.2f Fahrenheit",grado, formulasFahrenheit(grado, 2));
                            labelResultado.setText(txtSalida);
                        }              
                        default -> {
                            JOptionPane.showMessageDialog(null, "Seleccione una opción");
                        }
                    }
                        
                break;
                }
                
                case 3 -> {                           
                        switch (combo1.getSelectedIndex()) {
                        case 1 -> {
                            txtSalida = String.format("%.2f Celsius son = %.2f Kelvin",grado, formulasKelvin(grado, 1));
                            labelResultado.setText(txtSalida);
                        }
                        case 2 -> {
                            txtSalida = String.format("%.2f Fahrenheit son = %.2f Kelvin",grado, formulasKelvin(grado, 2));
                            labelResultado.setText(txtSalida);
                        }
                        case 3 -> {
                            txtSalida = String.format("%.2f Kelvin son = %.2f Kelvin",grado, formulasKelvin(grado, 3));
                            labelResultado.setText(txtSalida);
                        }              
                        default -> {
                            JOptionPane.showMessageDialog(null, "Seleccione una opción");
                        }
                    }
                
                break;
                }
                
                default -> {
                    JOptionPane.showMessageDialog(null, "Seleccione una opción");
                }
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Ingrese un valor valido", "Ocurrio un error", JOptionPane.ERROR_MESSAGE);
            fieldImporte.setText("");
            labelResultado.setText("");
        }
    }
   
    private Double formulasCelsius(double grado, int seleccion){
        return switch (seleccion) {
            case 2 -> (grado - 32)* 5/9;
            case 3 -> grado-273.15;
            default -> grado;
        };
    }   
    private Double formulasFahrenheit(double grado, int seleccion){
        return switch (seleccion) {
            case 1 -> (grado * 9/5) +32;
            case 3 -> (grado-273.15) * 9/5 +32;
            default -> grado;
        };
    }
    private Double formulasKelvin(double grado, int seleccion){
        return switch (seleccion) {
            case 1 -> grado + 273.15;
            case 2 -> (grado - 32) *5/9 +273.15;
            default -> grado;
        };
    }
    
    private void setCombos(JComboBox combos){
        for(String grado: grados){
            combos.addItem(grado);
        }
    }
    
    private void setImageLabel(JLabel labelName, String root, int width, int height){     
        ImageIcon image = new ImageIcon(Objects.requireNonNull(getClass().getResource(root)));
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH));
        labelName.setIcon(icon);
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnConvertir;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JLabel divisasImg;
    private javax.swing.JTextField fieldImporte;
    private javax.swing.JLabel labeImporte;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelDe;
    private javax.swing.JLabel labelInvertir;
    private javax.swing.JLabel labelResultado;
    private javax.swing.JTextField separador;
    private javax.swing.JLabel textTitulo;
    // End of variables declaration//GEN-END:variables
}
